# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/MainWindow.ui'
#
# Created: Mon Feb  7 00:25:54 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(306, 357)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 305, 351))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.btnStopAll = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnStopAll.setObjectName(_fromUtf8("btnStopAll"))
        self.verticalLayout.addWidget(self.btnStopAll)
        self.TabGroup = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.TabGroup.setObjectName(_fromUtf8("TabGroup"))
        self.apacheTab = QtGui.QWidget()
        self.apacheTab.setObjectName(_fromUtf8("apacheTab"))
        self.btnApacheStart = QtGui.QPushButton(self.apacheTab)
        self.btnApacheStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnApacheStart.setObjectName(_fromUtf8("btnApacheStart"))
        self.btnApacheStop = QtGui.QPushButton(self.apacheTab)
        self.btnApacheStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnApacheStop.setObjectName(_fromUtf8("btnApacheStop"))
        self.TabGroup.addTab(self.apacheTab, _fromUtf8(""))
        self.mysqlTab = QtGui.QWidget()
        self.mysqlTab.setObjectName(_fromUtf8("mysqlTab"))
        self.btnMysqlStop = QtGui.QPushButton(self.mysqlTab)
        self.btnMysqlStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnMysqlStop.setObjectName(_fromUtf8("btnMysqlStop"))
        self.btnMysqlStart = QtGui.QPushButton(self.mysqlTab)
        self.btnMysqlStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnMysqlStart.setObjectName(_fromUtf8("btnMysqlStart"))
        self.TabGroup.addTab(self.mysqlTab, _fromUtf8(""))
        self.postgreTab = QtGui.QWidget()
        self.postgreTab.setObjectName(_fromUtf8("postgreTab"))
        self.btnPostgreStop = QtGui.QPushButton(self.postgreTab)
        self.btnPostgreStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnPostgreStop.setObjectName(_fromUtf8("btnPostgreStop"))
        self.btnPostgreStart = QtGui.QPushButton(self.postgreTab)
        self.btnPostgreStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnPostgreStart.setObjectName(_fromUtf8("btnPostgreStart"))
        self.TabGroup.addTab(self.postgreTab, _fromUtf8(""))
        self.sshTab = QtGui.QWidget()
        self.sshTab.setObjectName(_fromUtf8("sshTab"))
        self.btnSshStop = QtGui.QPushButton(self.sshTab)
        self.btnSshStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnSshStop.setObjectName(_fromUtf8("btnSshStop"))
        self.btnSshStart = QtGui.QPushButton(self.sshTab)
        self.btnSshStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnSshStart.setObjectName(_fromUtf8("btnSshStart"))
        self.TabGroup.addTab(self.sshTab, _fromUtf8(""))
        self.postfixTab = QtGui.QWidget()
        self.postfixTab.setObjectName(_fromUtf8("postfixTab"))
        self.btnPostfixStart = QtGui.QPushButton(self.postfixTab)
        self.btnPostfixStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnPostfixStart.setObjectName(_fromUtf8("btnPostfixStart"))
        self.btnPostfixStop = QtGui.QPushButton(self.postfixTab)
        self.btnPostfixStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnPostfixStop.setObjectName(_fromUtf8("btnPostfixStop"))
        self.TabGroup.addTab(self.postfixTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.TabGroup)

        self.retranslateUi(Dialog)
        self.TabGroup.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Python Service Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "PyServices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Gestor de Servicios para KDE", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopAll.setText(QtGui.QApplication.translate("Dialog", "Detener &Todos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApacheStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApacheStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.apacheTab), QtGui.QApplication.translate("Dialog", "Apache", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMysqlStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMysqlStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.mysqlTab), QtGui.QApplication.translate("Dialog", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostgreStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostgreStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.postgreTab), QtGui.QApplication.translate("Dialog", "PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSshStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSshStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.sshTab), QtGui.QApplication.translate("Dialog", "SSH", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostfixStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostfixStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.postfixTab), QtGui.QApplication.translate("Dialog", "Postfix", None, QtGui.QApplication.UnicodeUTF8))

