# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/MainWindow.ui'
#
<<<<<<< HEAD
# Created: Tue Feb  8 22:47:07 2011
#      by: PyQt4 UI code generator 4.7.4
=======
# Created: Tue Feb  8 21:37:15 2011
#      by: PyQt4 UI code generator 4.8.1
>>>>>>> f5a5aff174cefeb271d13f2529046cdaf8bc208e
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(331, 388)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.btnStopAll = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnStopAll.setObjectName("btnStopAll")
        self.verticalLayout.addWidget(self.btnStopAll)
        self.TabGroup = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.TabGroup.setObjectName("TabGroup")
        self.apacheTab = QtGui.QWidget()
        self.apacheTab.setObjectName("apacheTab")
        self.btnApacheStart = QtGui.QPushButton(self.apacheTab)
        self.btnApacheStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnApacheStart.setObjectName("btnApacheStart")
        self.btnApacheStop = QtGui.QPushButton(self.apacheTab)
        self.btnApacheStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnApacheStop.setObjectName("btnApacheStop")
        self.TabGroup.addTab(self.apacheTab, "")
        self.mysqlTab = QtGui.QWidget()
        self.mysqlTab.setObjectName("mysqlTab")
        self.btnMysqlStop = QtGui.QPushButton(self.mysqlTab)
        self.btnMysqlStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnMysqlStop.setObjectName("btnMysqlStop")
        self.btnMysqlStart = QtGui.QPushButton(self.mysqlTab)
        self.btnMysqlStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnMysqlStart.setObjectName("btnMysqlStart")
        self.TabGroup.addTab(self.mysqlTab, "")
        self.postgreTab = QtGui.QWidget()
        self.postgreTab.setObjectName("postgreTab")
        self.btnPostgreStop = QtGui.QPushButton(self.postgreTab)
        self.btnPostgreStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnPostgreStop.setObjectName("btnPostgreStop")
        self.btnPostgreStart = QtGui.QPushButton(self.postgreTab)
        self.btnPostgreStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnPostgreStart.setObjectName("btnPostgreStart")
        self.TabGroup.addTab(self.postgreTab, "")
        self.sshTab = QtGui.QWidget()
        self.sshTab.setObjectName("sshTab")
        self.btnSshStop = QtGui.QPushButton(self.sshTab)
        self.btnSshStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnSshStop.setObjectName("btnSshStop")
        self.btnSshStart = QtGui.QPushButton(self.sshTab)
        self.btnSshStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnSshStart.setObjectName("btnSshStart")
        self.TabGroup.addTab(self.sshTab, "")
        self.postfixTab = QtGui.QWidget()
        self.postfixTab.setObjectName("postfixTab")
        self.btnPostfixStart = QtGui.QPushButton(self.postfixTab)
        self.btnPostfixStart.setGeometry(QtCore.QRect(80, 60, 121, 23))
        self.btnPostfixStart.setObjectName("btnPostfixStart")
        self.btnPostfixStop = QtGui.QPushButton(self.postfixTab)
        self.btnPostfixStop.setGeometry(QtCore.QRect(80, 100, 121, 23))
        self.btnPostfixStop.setObjectName("btnPostfixStop")
        self.TabGroup.addTab(self.postfixTab, "")
        self.verticalLayout.addWidget(self.TabGroup)

        self.retranslateUi(Dialog)
        self.TabGroup.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Python Service Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "PyServices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Gestor de Servicios para KDE", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopAll.setText(QtGui.QApplication.translate("Dialog", "Detener &Todos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApacheStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApacheStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.apacheTab), QtGui.QApplication.translate("Dialog", "Apache", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMysqlStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMysqlStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.mysqlTab), QtGui.QApplication.translate("Dialog", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostgreStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostgreStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.postgreTab), QtGui.QApplication.translate("Dialog", "PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSshStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSshStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.sshTab), QtGui.QApplication.translate("Dialog", "SSH", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostfixStart.setText(QtGui.QApplication.translate("Dialog", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPostfixStop.setText(QtGui.QApplication.translate("Dialog", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.TabGroup.setTabText(self.TabGroup.indexOf(self.postfixTab), QtGui.QApplication.translate("Dialog", "Postfix", None, QtGui.QApplication.UnicodeUTF8))

